export const Data = {
  name: "Ahmed Omran",
  role: "Front-End Developer",
  birthYear: "2001",
  img: "assets/img/My__img.png",
  location: { city: "Cairo", country: "(EG)" },
  status: "available for Freelance Projects",
  siteMap: ["Index", "About", "Projects", "Services", "Contact"],
  social: [
    { name: "Resume", link: "assets/Ahmed__Omran_cv.pdf" },
    { name: "Github", link: "https://github.com/2ao1-1" },
    { name: "Linkedin", link: "https://www.linkedin.com/in/2ao1" },
    { name: "Instagram", link: "https://www.instagram.com/10.7.2ao1/" },
    { name: "Whatsapp", link: "https://wa.me/201030960225" },
    { name: "Email", link: "mailto:omran.a.jr@gmail.com" },
  ],
  bio: "an aspiring Front-End Developer with a passion for creativity and a deep lovefor solving problems through design and technology. My journey into this field has been shaped by a lifelong fascination with art, an insatiable curiosity for technology, and a determination to turn my passion into a career.",
  story: {
    growing: [
      "Growing up in Egypt, I was always drawn to creative pursuits. From a young age, I loved sketching on paper, painting murals, and participating in school art competitions. These experiences taught me how to bring ideas to life visually and nurtured my love for self-expression.",
      "In middle school, my interest in technology began to bloom. I was captivated by the world of computers and dreamed of learning hacking, even though I didn’t know where to start. By high school, I started diving into the world of programming with the help of a friend, and I quickly found myself drawn to web development.",
      "I realized that front-end development was the perfect combination of design and technology—a space where I could create beautiful, interactive user experiences.",
      "Although I couldn’t pursue a university degree in programming, my passion didn’t stop there. I taught myself HTML, CSS, JavaScript, and React, taking every opportunity to enhance my skills through self-study and hands-on practice. Along the way, I explored other fields like marketing, but nothing resonated with me as much as coding and design.",
      "While I’ve faced challenges in finding my first opportunity in the tech industry, I see each obstacle as a stepping stone. These experiences have only deepened my commitment to becoming a skilled developer.",
    ],
    hope: [
      "Right now, I’m actively seeking opportunities to work as a Front-End Developer, where I can contribute to creating user-friendly, responsive websites while continuing to grow and learn. I’m excited to collaborate with teams that value creativity and innovation and to bring my passion for design and problem-solving to impactful projects.",
      "I believe that great web development is about more than just code—it’s about creating experiences that resonate with users. My goal is to combine my artistic background and technical skills to build solutions that are both functional and visually engaging.",
      "If you’re looking for a passionate, eager-to-learn developer who’s ready to make an impact, I’d love to connect and explore how I can contribute to your team.",
    ],
  },
  projects: [
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
    {
      title: "lol",
      img: "https://via.placeholder.com/150",
      bio: "hello world",
      description: "project description",
      skill: ["Html", "Css", "JavaScript", "Tailwind", "Bootstrap", "React"],
    },
  ],
};
